runtime: python312
entrypoint: gunicorn -b :$PORT config.wsgi

# In App Engine, you can configure your Supabase database credentials directly
# here, or set them securely in the Google Cloud Console.
env_variables:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  DB_NAME: "postgres"
  DB_USER: "postgres.nxplnygqfotgttuvzqpl"
  DB_PASSWORD: "Sunna@123#A"
  DB_HOST: "aws-1-ap-southeast-1.pooler.supabase.com"
  DB_PORT: "6543"
  GEE_CREDENTIALS_JSON: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDSP+9URW+KNEo3\nrkBxCEbGwVIs5iT7b2FSCGDVSgFmQV2nNak5PhrbVLcvLCz10WQ2FW/M9dVBhMUb\n8REgcMImJLCgEXsHPSLxmAnapX/plS4NbE2fLR6h4cAVbOw1s5B/Sjrt8iTOLhZe\nALfyjFp3TEcerGZF2jobb3mZ7opgVkK2al2qMfE+rqqpMBOsC3nKrEGQgtTBymeh\nmzFII1zM7A30N2zs0XV4C0T9mqAZooJd6KgLwYWZOCU112JNXZJfjcwASt6iM2sP\nzFRWYr/wCTVgWIr/oPtCAxuBhKMEsNmxn+UaVbq6KR1TLgo9Yb6yvOfX+CewofhS\n7t/kHrPdAgMBAAECggEAHq5EwvPk/HJ3+Bsd/UCbb2qLjtDAyc4tkfZ2BvnnLWBR\nhdJ/UMKe0a3Rk3krUG3PZVMIfwzKo2Z4CwVJHgZGVqGZAqq6XMqPnFi262imO1RR\nJZVN2HIRm8bhLF86MvXympie89UXiNzR18LcFPFlTC5d3HyE6iGXxCQmxw83synv\nbeqcZGkjOTP5rov7TG2+iVOkdvkGSLa3rFjYGkf3BnyTbe0c7QlzCTWFyan7KnGp\nWFfA7+Wv1NED2RANOfBmKDh0FhOrHl2Y2b0ZFkNu1V3pBZ94hWTeSVkzU91ElKTL\ngtBVWSQ0a95NgndCT/zWiWDXJreJcuvZxa3Fy7+5cwKBgQD5CJA1v/BNWwRv625F\nLLCOhAbKcuieukLTXV0Ka7QpvomyAZdGj7oh74kAvXVpPryeJBVUReNjYucJRB5P\nsoj5XlY0WKSleYz4v9ZmEFgIZeodF+GtaftLrqMeBlO/simy2DQ7XXe+wX7HAGQV\ny8OY1WJIim3/O8ReadQxQffvwwKBgQDYIZ/mRzxc++YBqC1kpOIkCVrvJGpNUzDJ\nF6VmJtXf/rjS0B6znd/ENfQSnevhfhVDj8NP7XfirVw2snw09lyecu0x1x3Hf8Mm\nX+qBW0TJ2sE/Z304Hnog9gRbaPIapEg3CpJTYiks1c6O5CyrX2yxS7Jhv1BcS3Jj\nb51MqQsz3wKBgCdCrlmK9Pt9CeoLF8tYDE2ritaH3xyHCNoBshVefXzHSTYDAjJh\nnlqTROoU9FmvRlU4IxSyH/MfOIVBc/Xkk6ucr8J45xwfWZYtyEM2+Gn6hzom9bE9\nMBzyX0zwemuSTvifFTz2s1YjczU0XpMBGMkTevcsu8KtTXwE+yr413m5AoGAHXCf\nFj/30faiAvHElSP8hcocb9y2+idtysaEyiBaG7PXuyeMNw03MMPkpjCKs+F3xgcs\nJJQFM4RHvk+bqZ8xSIgBFTvnG4ikrXJ9P/eNrC03C4ruPJmyKxE30Le/2q8sAwtW\nmTMSxr+s7jvYddN+u7vC5Zuot5mzUCYg+BNCqmMCgYBumBUgzOOcIIn2LZRRbvnn\nLlWeG2i6JEtPwRhqyIYMSvkn3w2Z9fMRmtM31VwvGHZJF9BimF3GTtnLAt6T7x7R\nl41zWMxhXcmPniha4WAb8P92Lq51CliwtYTbZ4yZO01LrXqYE3ED6y3Ecc+b7jGq\nsEv2p1UsHvJlCeANHrKK8g==\n-----END PRIVATE KEY-----\n"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_USER: "deforestation.ai.wilpattu@gmail.com"
  EMAIL_HOST_PASSWORD: "gnkjlqagcfhnhyjg"
  REPORT_RECIPIENT_EMAIL: "udithasunimal18@gmail.com"
