# Generated by Django 6.0.5 on 2026-06-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisturbanceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(max_length=50, unique=True)),
                ('detection_date', models.DateField()),
                ('ndvi_change', models.FloatField()),
                ('area_m2', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitored', 'Monitored'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('confidence', models.FloatField()),
                ('geometry', models.JSONField()),
            ],
        ),
    ]
