# Generated by Django 6.0.5 on 2026-06-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disturbancearea',
            name='area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='disturbance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='polygon_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='protected_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='reforestation_priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='reforestation_suitability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='risk_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='road_distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='village_distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='vulnerability_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='waterway_distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disturbancearea',
            name='xai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
